// © QuantitativeAlpha
//@version=6
indicator(title = 'Global Liquidity Index', shorttitle = 'GLI', overlay = true, scale = scale.left)
fed_active = input.bool(true, title = 'FED (Federal Reserve System)')
tga_active = input.bool(true, title = 'TGA (Treasury General Account)')
rrp_active = input.bool(true, title = 'RRP (Reverse Repurchases)')
ecb_active = input.bool(true, title = 'ECB (European Central Bank)')
pbc_active = input.bool(true, title = 'PBC (People\'s Bank of China)')
boj_active = input.bool(true, title = 'BOJ (Bank of Japan)')
other_active = input.bool(true, title = 'Smaller Central Banks')
usa_active = input.bool(true, title = 'USM2 (USA Money Supply)')
europe_active = input.bool(true, title = 'EUM2 (Europe Money Supply)')
china_active = input.bool(true, title = 'CNM2 (China Money Supply)')
japan_active = input.bool(true, title = 'JPM2 (Japan Money Supply)')
other_m2_active = input.bool(true, title = 'Smaller M2 Economies')
sma_input_raw = input.int(0, title = 'SMA Length', minval = 0)
roc_input = input.int(0, title = 'ROC Length', minval = 0)
corr_length_input = input.string('3M', title = 'Correlation', options = ['3M', '6M', '9M', '1Y', '3Y', '5Y', '10Y'])
offset_input = input.int(0, title = 'Offset Bars')
strategy_type = input.string('EMA', title = 'Trend Type', options = ['EMA', 'SMA', 'RMA', 'WMA'])
fast_input = input.int(30, title = 'Fast Length', minval = 1)
slow_input = input.int(60, title = 'Slow Length', minval = 2)
fed = fed_active ? request.security('ECONOMICS:USCBBS', 'D', close, currency = currency.USD) : 0
rrp = rrp_active ? request.security('FRED:RRPONTSYD', 'D', close, currency = currency.USD) : 0
tga = tga_active ? request.security('FRED:WTREGEN', 'D', close, currency = currency.USD) : 0
ecb = ecb_active ? request.security('ECONOMICS:EUCBBS * FX_IDC:EURUSD', 'D', close, currency = currency.USD) : 0
pbc = pbc_active ? request.security('ECONOMICS:CNCBBS * FX_IDC:CNYUSD', 'D', close, currency = currency.USD) : 0
boj = boj_active ? request.security('ECONOMICS:JPCBBS * FX_IDC:JPYUSD', 'D', close, currency = currency.USD) : 0
boe = other_active ? request.security('ECONOMICS:GBCBBS * FX_IDC:GBPUSD', 'D', close, currency = currency.USD) : 0
boc = other_active ? request.security('ECONOMICS:CACBBS * FX_IDC:CADUSD', 'D', close, currency = currency.USD) : 0
rba = other_active ? request.security('ECONOMICS:AUCBBS * FX_IDC:AUDUSD', 'D', close, currency = currency.USD) : 0
rbi = other_active ? request.security('ECONOMICS:INCBBS * FX_IDC:INRUSD', 'D', close, currency = currency.USD) : 0
snb = other_active ? request.security('ECONOMICS:CHCBBS * FX_IDC:CHFUSD', 'D', close, currency = currency.USD) : 0
cbr = other_active ? request.security('ECONOMICS:RUCBBS * FX_IDC:RUBUSD', 'D', close, currency = currency.USD) : 0
bcb = other_active ? request.security('ECONOMICS:BRCBBS * FX_IDC:BRLUSD', 'D', close, currency = currency.USD) : 0
bok = other_active ? request.security('ECONOMICS:KRCBBS * FX_IDC:KRWUSD', 'D', close, currency = currency.USD) : 0
rbzn = other_active ? request.security('ECONOMICS:NZCBBS * FX_IDC:NZDUSD', 'D', close, currency = currency.USD) : 0
sr = other_active ? request.security('ECONOMICS:SECBBS * FX_IDC:SEKUSD', 'D', close, currency = currency.USD) : 0
bnm = other_active ? request.security('ECONOMICS:MYCBBS * FX_IDC:MYRUSD', 'D', close, currency = currency.USD) : 0
usa = usa_active ? request.security('ECONOMICS:USM2', 'D', close, currency = currency.USD) : 0
eu = europe_active ? request.security('ECONOMICS:EUM2 * FX_IDC:EURUSD', 'D', close, currency = currency.USD) : 0
china = china_active ? request.security('ECONOMICS:CNM2 * FX_IDC:CNYUSD', 'D', close, currency = currency.USD) : 0
japan = japan_active ? request.security('ECONOMICS:JPM2 * FX_IDC:JPYUSD', 'D', close, currency = currency.USD) : 0
uk = other_m2_active ? request.security('ECONOMICS:GBM2 * FX_IDC:GBPUSD', 'D', close, currency = currency.USD) : 0
canada = other_m2_active ? request.security('ECONOMICS:CAM2 * FX_IDC:CADUSD', 'D', close, currency = currency.USD) : 0
australia = other_m2_active ? request.security('ECONOMICS:AUM3 * FX_IDC:AUDUSD', 'D', close, currency = currency.USD) : 0
india = other_m2_active ? request.security('ECONOMICS:INM2 * FX_IDC:INRUSD', 'D', close, currency = currency.USD) : 0
switzerland = other_m2_active ? request.security('ECONOMICS:CHM2 * FX_IDC:CHFUSD', 'D', close, currency = currency.USD) : 0
russia = other_m2_active ? request.security('ECONOMICS:RUM2 * FX_IDC:RUBUSD', 'D', close, currency = currency.USD) : 0
brazil = other_m2_active ? request.security('ECONOMICS:BRM2 * FX_IDC:BRLUSD', 'D', close, currency = currency.USD) : 0
korea = other_m2_active ? request.security('ECONOMICS:KRM2 * FX_IDC:KRWUSD', 'D', close, currency = currency.USD) : 0
mexico = other_m2_active ? request.security('ECONOMICS:MXM2 * FX_IDC:MXNUSD', 'D', close, currency = currency.USD) : 0
indonesia = other_m2_active ? request.security('ECONOMICS:IDM2 * FX_IDC:IDRUSD', 'D', close, currency = currency.USD) : 0
africa = other_m2_active ? request.security('ECONOMICS:ZAM2 * FX_IDC:ZARUSD', 'D', close, currency = currency.USD) : 0
malaysia = other_m2_active ? request.security('ECONOMICS:MYM2 * FX_IDC:MYRUSD', 'D', close, currency = currency.USD) : 0
sweden = other_m2_active ? request.security('ECONOMICS:SEM2 * FX_IDC:SEKUSD', 'D', close, currency = currency.USD) : 0
total = (fed - rrp - tga + boj + pbc + boe + ecb + rbi + boc + rba + snb + cbr + bcb + bok + rbzn + sr + bnm + usa + eu + china + japan + uk + canada + australia + india + switzerland + russia + brazil + korea + mexico + indonesia + africa + malaysia + sweden) / 1000000000000
sma_input = sma_input_raw == 0 ? 1 : sma_input_raw
total_sma = ta.sma(total, sma_input)
roc_sma = roc_input == 0 ? total_sma : ta.sma(ta.roc(total, roc_input), sma_input)
plot(roc_sma, title = 'GLI Line', color = color.yellow, linewidth = 2, offset = offset_input)
fast = strategy_type == 'SMA' ? ta.sma(total_sma, fast_input) : strategy_type == 'WMA' ? ta.wma(total_sma, fast_input) : strategy_type == 'RMA' ? ta.rma(total_sma, fast_input) : ta.ema(total_sma, fast_input)
slow = strategy_type == 'SMA' ? ta.sma(total_sma, slow_input) : strategy_type == 'WMA' ? ta.wma(total_sma, slow_input) : strategy_type == 'RMA' ? ta.rma(total_sma, slow_input) : ta.ema(total_sma, slow_input)
bull = fast > slow
bear = fast < slow
is_bull = bear[1] and bull
is_bear = bull[1] and bear
is_crypto = syminfo.type == 'crypto'
trading_days = is_crypto ? 30 : 21
corr_length = corr_length_input == '6M' ? trading_days * 6 : corr_length_input == '9M' ? trading_days * 9 : corr_length_input == '1Y' ? trading_days * 12 : corr_length_input == '3Y' ? trading_days * 36 : corr_length_input == '5Y' ? trading_days * 60 : corr_length_input == '10Y' ? trading_days * 120 : trading_days * 3
gli_corr = offset_input > 0 ? roc_sma[math.abs(offset_input)] : roc_sma
price_sma = ta.sma(close, sma_input)
roc_price_sma = roc_input == 0 ? price_sma : ta.sma(ta.roc(close, roc_input), sma_input)
price_corr = offset_input < 0 ? roc_price_sma[math.abs(offset_input)] : roc_price_sma
corr = ta.correlation(gli_corr, price_corr, corr_length)
corr_text = str.tostring(corr, '#.#')
var table t = table.new(position.bottom_right, 1, 3, border_width = 2)
table.cell(t, 0, 2, text = '', width = 14, text_color = color.new(color.white, 100), bgcolor = color.new(color.white, 100))
table.cell(t, 0, 0, text = bull ? 'BULL' : 'BEAR', width = 14, text_color = color.white, bgcolor = bull ? color.green : bear ? color.red : color.gray)
table.cell(t, 0, 1, text = corr_text, width = 14, text_color = color.white, bgcolor = corr > 0.7 ? color.green : corr < -0.7 ? color.red : color.gray)
alertcondition(is_bull, title = 'GLI Trend Bullish', message = 'Global Liquidity Bullish Trend!')
alertcondition(is_bear, title = 'GLI Trend Bearish', message = 'Global Liquidity Bearish Trend!')