// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © toodegrees
//@version=5
indicator( "ICT Algorithmic Macro Tracker° (Open-Source) by toodegrees"
		 , shorttitle = "Macro Tracker°"
		 , overlay    = true
		 , max_lines_count=500
		 , max_labels_count=500
		 , max_boxes_count=500)


//#region[GLOBAL]
var line[]  EXT = array.new_line()
var label[] LBL = array.new_label()
oneDayMS        = 86400000
oneBarMS        = time_close-time
noColor         =color.new(#ffffff,100)
one             = ta.highest(timeframe.in_seconds("15")/timeframe.in_seconds(timeframe.period))+syminfo.mintick*10
y_btm_Line1     = one
y_top_Line1     = one+syminfo.mintick*5
//#endregion


//#region[INPUTS]
_macroC =  input.color(color.new(#000000,0),  title="Macro Color",        inline='main')
_mode   = input.string("On Chart",              title="",                   inline='main', options=["On Chart", "New Pane"], tooltip='When "New Pane" is selected, make sure you move the indicator to a New Pane as well, it is not automatic.')

_showL  =   input.bool(true,                    title="Macro Label?",       inline='sh')
_mTxt   =   input.bool(false,                   title="Show Time?",         inline='sh')
_extt   =	input.bool(false,                   title="Macro Projections?", inline='sh', tooltip='Extends On Chart Macro lines towards price.')

_bgm    =  input.color(color.new(#4caf50,70), title="Macro Color",     inline='bc',     tooltip='Visible only in "New Pane" mode')
//#endregion


//#region[FUNCTIONS]
time_isMacro(int H_start, int M_start, int H_end, int M_end) =>
    h = hour(time, "America/New_York")
    m = minute(time, "America/New_York")
	h==H_start ? (H_start!=H_end ? m>=M_start : m>=M_start and m<M_end) : (h>H_start ? (h==H_end ? m<M_end : h<H_end) : false)


_controlMacroLine(line[] _lines, label[] _lbl, bool _time) =>
	if _time
		_lbl.last().set_x(math.round(math.avg(_lines.get(_lines.size()-2).get_x1(),time)))
		if high>_lines.last().get_y2()-syminfo.mintick*10
			_lines.get(_lines.size()-2).set_y2(high+(syminfo.mintick*10))
			_lines.last().set_y1(high+(syminfo.mintick*10))
			_lines.last().set_y2(high+(syminfo.mintick*10))
			LBL.last().set_y(high+(syminfo.mintick*10))
		if na or _lines.last().get_x2() == time
			_lines.last().set_x2(time+oneBarMS)

_controlMacroBox(box[] _boxes, bool _time, bool _friday) =>
	dly = _friday?oneDayMS*3:oneDayMS
	if na or _time
		_boxes.last().set_right(time+dly)

method memoryCleanLine(line[] A) =>
	if A.size()>300
		for i=0 to 3
			A.shift().delete()
method memoryCleanLabel(label[] A) =>
	if A.size()>100
		A.shift().delete()

macroOC(line[] LINES, bool _time, string _kzTime, bool _friday)=>
	dly  = _friday?oneDayMS*3:oneDayMS
	_txt = _mTxt?"MACRO"+"\n"+_kzTime:"MACRO"
	_tt  = "MACRO\n"+_kzTime

	// Overlay False
	if not _time[1] and _time
		_vline1 = line.new(time,y_btm_Line1,time,y_top_Line1,xloc=xloc.bar_time,color=_macroC)
		LINES.push(_vline1)
		_hline = line.new(time,y_top_Line1,time+oneBarMS,y_top_Line1,xloc=xloc.bar_time,color=_macroC)
		LINES.push(_hline)
		if _extt
			EXT.push(line.new(time,high,time,_vline1.get_y2(),xloc=xloc.bar_time,color=_macroC,style=line.style_dotted))

		if _mode=="On Chart"
			LBL.push(label.new(time
							 , LINES.get(LINES.size()-2).get_y2()
							 , _showL?_txt:""
							 , tooltip=_tt
							 , xloc=xloc.bar_time
							 , style=label.style_label_down
							 , color=noColor
							 , textcolor=_macroC
							 , size=size.small))

	if _time[1] and not _time and LINES.size()>0 and LBL.size()>0
		_vline2 = line.new(time,y_btm_Line1,time,y_top_Line1,xloc=xloc.bar_time,color=_macroC)
		LBL.last().set_x(math.round(math.avg(LINES.get(LINES.size()-2).get_x1(),time)))
		if y_top_Line1 > LINES.get(LINES.size()-2).get_y2()
			LINES.get(LINES.size()-2).set_y2(y_top_Line1)
			LINES.last().set_y1(y_top_Line1)
			LINES.last().set_y2(y_top_Line1)
			LBL.last().set_y(y_top_Line1)
		else if y_top_Line1 < LINES.get(LINES.size()-2).get_y2()
			_vline2.set_y2(LINES.get(LINES.size()-2).get_y2())
		if _extt
			EXT.push(line.new(time,high,time,_vline2.get_y2(),xloc=xloc.bar_time,color=_macroC,style=line.style_dotted))

		LINES.push(_vline2)

	if LINES.size()>0 and LBL.size()>0
		_controlMacroLine(LINES, LBL, _time)
		

macroNP(box[] BOXES, bool _time, string _kzTime, bool _friday)=>
	dly  = _friday?86400000*3:86400000
	_col = _bgm
	_tt  = "MACRO\n"+_kzTime
	end  = not _time and _time[1]

	// Overlay False
	var _plotNP = false
	if not _time[1] and _time
		_macro = box.new(time+dly,2,time+dly,0,_macroC,xloc=xloc.bar_time,bgcolor=_col)
		BOXES.push(_macro)
		_plotNP := true

	if _time[1] and not _time and BOXES.size()>0
		_controlMacroBox(BOXES, true, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
		_plotNP := false
		macroL = label.new(math.round(math.avg(BOXES.last().get_left(),BOXES.last().get_right()))
					     , 1
						 , xloc=xloc.bar_time
						 , style=label.style_label_center
						 , color=noColor
						 , tooltip=_tt
						 , text='ⓘ\n\n\n\n\n\n'
						 , textcolor=_macroC
						 , size=size.small)

	if _time and _plotNP
		_controlMacroBox(BOXES, _time, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
//#endregion


//#region[LOGIC]
show1              = input.bool(false, title="00:50 - 01:10", group="Hourly Macros")
var line[] _LINES1 = array.new_line()
var box[] _BOXES1  = array.new_box()
time1              = time_isMacro(0, 50, 1, 10)
lbl1               = "00:50 - 1:10"

show2              = input.bool(false, title="01:50 - 02:10", group="Hourly Macros")
var line[] _LINES2 = array.new_line()
var box[] _BOXES2  = array.new_box()
time2              = time_isMacro(1, 50, 2, 10)
lbl2               = "1:50 - 2:10"

show3              = input.bool(true, title="02:50 - 03:10", group="Hourly Macros")
var line[] _LINES3 = array.new_line()
var box[] _BOXES3  = array.new_box()
time3              = time_isMacro(2, 50, 3, 10)
lbl3               = "2:50 - 3:10"

show4              = input.bool(true, title="03:50 - 04:10", group="Hourly Macros")
var line[] _LINES4 = array.new_line()
var box[] _BOXES4  = array.new_box()
time4              = time_isMacro(3, 50, 4, 10)
lbl4               = "3:50 - 4:10"

show5              = input.bool(true, title="04:50 - 05:10", group="Hourly Macros")
var line[] _LINES5 = array.new_line()
var box[] _BOXES5  = array.new_box()
time5              = time_isMacro(4, 50, 5, 10)
lbl5               = "4:50 - 5:10"

show6              = input.bool(false, title="05:50 - 06:10", group="Hourly Macros")
var line[] _LINES6 = array.new_line()
var box[] _BOXES6  = array.new_box()
time6              = time_isMacro(5, 50, 6, 10)
lbl6               = "5:50 - 6:10"

show7              = input.bool(false, title="06:50 - 07:10", group="Hourly Macros")
var line[] _LINES7 = array.new_line()
var box[] _BOXES7  = array.new_box()
time7              = time_isMacro(6, 50, 7, 10)
lbl7               = "6:50 - 7:10"

show8              = input.bool(false, title="07:50 - 08:10", group="Hourly Macros")
var line[] _LINES8 = array.new_line()
var box[] _BOXES8  = array.new_box()
time8              = time_isMacro(7, 50, 8, 10)
lbl8               = "7:50 - 8:10"

show9              = input.bool(false, title="08:50 - 09:10", group="Hourly Macros")
var line[] _LINES9 = array.new_line()
var box[] _BOXES9  = array.new_box()
time9              = time_isMacro(8, 50, 9, 10)
lbl9               = "8:50 - 9:10"

show10              = input.bool(true, title="09:50 - 10:10", group="Hourly Macros")
var line[] _LINES10 = array.new_line()
var box[] _BOXES10  = array.new_box()
time10              = time_isMacro(9, 50, 10, 10)
lbl10               = "9:50 - 10:10"

show11              = input.bool(true, title="10:50 - 11:10", group="Hourly Macros")
var line[] _LINES11 = array.new_line()
var box[] _BOXES11  = array.new_box()
time11              = time_isMacro(10, 50, 11, 10)
lbl11               = "10:50 - 11:10"

show12              = input.bool(true, title="11:50 - 12:10", group="Hourly Macros")
var line[] _LINES12 = array.new_line()
var box[] _BOXES12  = array.new_box()
time12              = time_isMacro(11, 50, 12, 10)
lbl12               = "11:50 - 12:10"

show13              = input.bool(true, title="12:50 - 13:10", group="Hourly Macros")
var line[] _LINES13 = array.new_line()
var box[] _BOXES13  = array.new_box()
time13              = time_isMacro(12, 50, 13, 10)
lbl13               = "12:50 - 13:10"

show14              = input.bool(true, title="13:50 - 14:10", group="Hourly Macros")
var line[] _LINES14 = array.new_line()
var box[] _BOXES14  = array.new_box()
time14              = time_isMacro(13, 50, 14, 10)
lbl14               = "13:50 - 14:10"

show17              = input.bool(false, title="16:50 - 17:10", group="Hourly Macros")
var line[] _LINES17 = array.new_line()
var box[] _BOXES17  = array.new_box()
time17              = time_isMacro(16, 50, 17, 10)
lbl17               = "16:50 - 17:10"

show18              = input.bool(false, title="17:50 - 18:10", group="Hourly Macros")
var line[] _LINES18 = array.new_line()
var box[] _BOXES18  = array.new_box()
time18              = time_isMacro(17, 50, 18, 10)
lbl18               = "17:50 - 18:10"

show19              = input.bool(false, title="18:50 - 19:10", group="Hourly Macros")
var line[] _LINES19 = array.new_line()
var box[] _BOXES19  = array.new_box()
time19              = time_isMacro(18, 50, 19, 10)
lbl19               = "18:50 - 19:10"

show20              = input.bool(false, title="19:50 - 20:10", group="Hourly Macros")
var line[] _LINES20 = array.new_line()
var box[] _BOXES20  = array.new_box()
time20              = time_isMacro(19, 50, 20, 10)
lbl20               = "19:50 - 20:10"

show21              = input.bool(false, title="20:50 - 21:10", group="Hourly Macros")
var line[] _LINES21 = array.new_line()
var box[] _BOXES21  = array.new_box()
time21              = time_isMacro(20, 50, 21, 10)
lbl21               = "20:50 - 21:10"

show22              = input.bool(false, title="21:50 - 22:10", group="Hourly Macros")
var line[] _LINES22 = array.new_line()
var box[] _BOXES22  = array.new_box()
time22              = time_isMacro(21, 50, 22, 10)
lbl22               = "21:50 - 22:10"

show23              = input.bool(false, title="22:50 - 23:10", group="Hourly Macros")
var line[] _LINES23 = array.new_line()
var box[] _BOXES23  = array.new_box()
time23              = time_isMacro(22, 50, 23, 10)
lbl23               = "22:50 - 23:10"

show24              = input.bool(false, title="23:50 - 00:10", group="Hourly Macros")
var line[] _LINES24 = array.new_line()
var box[] _BOXES24  = array.new_box()
time24              = time_isMacro(23, 50, 0, 10)
lbl24               = "23:50 - 00:10"


show15              = input.bool(true, title="14:50 - 15:10", group="Last Hour NY PM Macros")
var line[] _LINES15 = array.new_line()
var box[] _BOXES15  = array.new_box()
time15              = time_isMacro(14, 50, 15, 10)
lbl15               = "14:50 - 15:10"

showPM1              = input.bool(true, title="15:15 - 15:45", group="Last Hour NY PM Macros")
var line[] _LINESPM1 = array.new_line()
var box[] _BOXESPM1  = array.new_box()
timePM1              = time_isMacro(15, 15, 15, 45)
lblPM1               = "15:15 - 15:45"

show16              = input.bool(true, title="15:50 - 16:10", group="Last Hour NY PM Macros")
var line[] _LINES16 = array.new_line()
var box[] _BOXES16  = array.new_box()
time16              = time_isMacro(15, 50, 16, 10)
lbl16               = "15:50 - 16:10"

// 																		                        //\//////////////////////////////////////////////////////////////////////////////////////////////////////////////\///
//                                                                                              //  INSTRUCTIONS TO ADD CUSTOM MACROs (PART 1):                                                                    //
//                                                                                              //  1.1) Copy these four lines of code and add them below the instruction box -> // CUSTOM MACROS;                 //
// var line[] _lines_YourMacroName = array.new_line()                                           //       Make sure the text is not gray like these instructions. To do that, remove the '//' in front.             //
// var box[] _boxes_YourMacroName  = array.new_box()                                            //  1.2) Replace 'YourMacroName' with whatever you want in these four lines.                                       //
// _time_YourMacroName            = time_isMacro(startHour, startMinute, endHour, endMinute)    //  1.3) Add your macro time window in the format: "hhmm-hhmm:1234567"                                             //
// _lbl_YourMacroName             = "hh:mm - hh:mm"                                             //  1.4) Add your macro time text in _lbl_YourMacroName, this will be displayed in the tooltips,                   //
// 																		                        //       and in the MACRO label on chart, if toggled on.                                                           //
// 																		                        //                                                                                                                 //
// 																		                        ///\//////////////////////////////////////////.   PART 2 BELOW   .////////////////////////////////////////////////\//

// CUSTOM MACROS
// Your custom macros go here
//#endregion


//#region[PLOT]
if _mode=="On Chart"
	if show1
		macroOC(_LINES1, time1, lbl1, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       //\////////////////////////////////////////////////////////////////////////////\///
	if show2																							  //  INSTRUCTIONS TO ADD CUSTOM MACROs (PART 2):                                  //
		macroOC(_LINES2, time2, lbl2, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       //  2.1) Find line 364 under "CUSTOM MACROS ON CHART PLOT" title.                //
	if show3																							  //  2.2) Copy it to the following line, remove '//' and replace 'YourMacroName'  //
		macroOC(_LINES3, time3, lbl3, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       //       with what you used above in step (1.2).                                 //
	if show4																							  //  2.3) Make sure the beginning of the line is aligned with all the ones above; //
		macroOC(_LINES4, time4, lbl4, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       //       To do that press 'Tab' once, or add spaces until they match.            //
	if show5																							  //                                                                               //
		macroOC(_LINES5, time5, lbl5, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       ///\/////////////////////////.   CONT'D BELOW   .///////////////////////////////\//
	if show6
		macroOC(_LINES6, time6, lbl6, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       
	if show7
		macroOC(_LINES7, time7, lbl7, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       
	if show8
		macroOC(_LINES8, time8, lbl8, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       
	if show9
		macroOC(_LINES9, time9, lbl9, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       
	if show10
		macroOC(_LINES10, time10, lbl10, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show11
		macroOC(_LINES11, time11, lbl11, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show12
		macroOC(_LINES12, time12, lbl12, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show13
		macroOC(_LINES13, time13, lbl13, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show14
		macroOC(_LINES14, time14, lbl14, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show15
		macroOC(_LINES15, time15, lbl15, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show16
		macroOC(_LINES16, time16, lbl16, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show17
		macroOC(_LINES17, time17, lbl17, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show18
		macroOC(_LINES18, time18, lbl18, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show19
		macroOC(_LINES19, time19, lbl19, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show20
		macroOC(_LINES20, time20, lbl20, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show21
		macroOC(_LINES21, time21, lbl21, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show22
		macroOC(_LINES22, time22, lbl22, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show23
		macroOC(_LINES23, time23, lbl23, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if show24
		macroOC(_LINES24, time24, lbl24, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')
	if showPM1
		macroOC(_LINESPM1, timePM1, lblPM1, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')

	// CUSTOM MACROS ON CHART PLOT
	// macroOC(_lines_YourMacroName, _timeYourMacroName, _lblYourMacroName, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto', '')


else
	if show1
		macroNP(_BOXES1, time1, lbl1, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       //\//////////////////////////.      \/\/\/      .//////////////////////////////\///
	if show2																							  //                                                                               //
		macroNP(_BOXES2, time2, lbl2, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       //  2.4) Find line 420 under "CUSTOM MACROS NEW PANE PLOT" title.                //														          
	if show3																							  //  2.5) Copy it to the following line, remove '//' and replace 'YourMacroName'  //
		macroNP(_BOXES3, time3, lbl3, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       //       with what you used above in step (1.2).                                 //
	if show4																							  //  2.6) Make sure the beginning of the line is aligned with all the ones above; //
		macroNP(_BOXES4, time4, lbl4, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       //       To do that press 'Tab' once, or add spaces until they match.            //
	if show5																							  //                                                                               //
		macroNP(_BOXES5, time5, lbl5, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       ///\///////////////////////.    LAST STEP BELOW   ./////////////////////////////\//
	if show6
		macroNP(_BOXES6, time6, lbl6, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')       
	if show7
		macroNP(_BOXES7, time7, lbl7, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto') 	  
	if show8
		macroNP(_BOXES8, time8, lbl8, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show9
		macroNP(_BOXES9, time9, lbl9, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show10
		macroNP(_BOXES10, time10, lbl10, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show11
		macroNP(_BOXES11, time11, lbl11, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show12
		macroNP(_BOXES12, time12, lbl12, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show13
		macroNP(_BOXES13, time13, lbl13, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show14
		macroNP(_BOXES14, time14, lbl14, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show15
		macroNP(_BOXES15, time15, lbl15, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show16
		macroNP(_BOXES16, time16, lbl16, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show17
		macroNP(_BOXES17, time17, lbl17, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show18
		macroNP(_BOXES18, time18, lbl18, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show19
		macroNP(_BOXES19, time19, lbl19, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show20
		macroNP(_BOXES20, time20, lbl20, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show21
		macroNP(_BOXES21, time21, lbl21, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show22
		macroNP(_BOXES22, time22, lbl22, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show23
		macroNP(_BOXES23, time23, lbl23, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if show24
		macroNP(_BOXES24, time24, lbl24, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 
	if showPM1
		macroNP(_BOXESPM1, timePM1, lblPM1, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto')																										 

	// CUSTOM MACROS NEW PANE PLOT
	// macroNP(_boxesYourMacroName, _timeYourMacroName, _lblYourMacroName, dayofweek(time)==dayofweek.friday and syminfo.type!='crypto', '')
//#endregion


//#region[MEMORY CLEAN UP]
if show1
	_LINES1.memoryCleanLine()
if show2          
	_LINES2.memoryCleanLine()
if show3                    		//\//////////////////////////.      \/\/\/      .//////////////////////////////\///        
	_LINES3.memoryCleanLine()		//                                                                               //        
if show4                    		//  2.4) Find line 477 under "CUSTOM MACROS LINE CLEAN UP" title.                //
	_LINES4.memoryCleanLine()		//  2.5) Copy it to the following line, remove '//' and replace 'YourMacroName'  //
if show5                    		//       with what you used above in step (1.2).                                 //
	_LINES5.memoryCleanLine()       //                                                                               //
if show6                     		///\/////////////////////.    YOU ARE DONE! GLGT    .///////////////////////////\//
	_LINES6.memoryCleanLine()
if show7                    
	_LINES7.memoryCleanLine()
if show8				    
	_LINES8.memoryCleanLine()
if show9				    
	_LINES9.memoryCleanLine()
if show10
	_LINES10.memoryCleanLine()
if show11
	_LINES11.memoryCleanLine()
if show12
	_LINES12.memoryCleanLine()
if show13
	_LINES13.memoryCleanLine()
if show14
	_LINES14.memoryCleanLine()
if show15
	_LINES15.memoryCleanLine()
if show16
	_LINES16.memoryCleanLine()
if show17
	_LINES17.memoryCleanLine()
if show18
	_LINES18.memoryCleanLine()
if show19
	_LINES19.memoryCleanLine()
if show20
	_LINES20.memoryCleanLine()
if show21
	_LINES21.memoryCleanLine()
if show22
	_LINES22.memoryCleanLine()
if show23
	_LINES23.memoryCleanLine()
if show24
	_LINES24.memoryCleanLine()
if showPM1
	_LINESPM1.memoryCleanLine()

// CUSTOM MACROS LINE CLEAN UP
//_lines_YourMacroName.memoryCleanLine()


EXT.memoryCleanLine()
LBL.memoryCleanLabel()
//#endregion