study("Matrix Series",shorttitle="MS",precision=1)
Smoother=input(5)
nn = Smoother
//--Sup/Res Detail
SupResPeriod = input(50)
SupResPercentage =input(100)
PricePeriod = input(16)
ob = input(200,title="Overbought")
os = input(-200,title="Oversold")
OBOS= input(type=bool,defval=false,title="Show OB/OS") 
dynamic=input(true,title="Dynamic zones")
ys1 = ( high + low + close * 2 ) / 4
rk3 = ema( ys1, nn )
rk4 = stdev(ys1, nn)
rk5 = (ys1 - rk3 ) * 200 / rk4
rk6 = ema( rk5, nn )
up = ema(rk6, nn )
down = ema( up, nn )
Oo = iff( up < down, up, down )
Hh = Oo
Ll = iff( up < down, down, up )
Cc = Ll
vcolor= Oo > Cc ? red : up > down? green:red 

plotcandle(Oo,Hh,Ll,Cc,color=vcolor)


//-------S/R Zones------
Lookback = SupResPeriod
PerCent = SupResPercentage
Pds = PricePeriod

C3 = cci(close,Pds )

Osc = C3
Value1 = Osc
Value2 = highest( Value1, Lookback )
Value3 = lowest( Value1, Lookback )
Value4 = Value2 - Value3
Value5 = Value4 * ( PerCent / 100 )
ResistanceLine = Value3 + Value5
SupportLine = Value2 - Value5
plot(dynamic?ResistanceLine:na,color=green,transp=0)
plot(dynamic?SupportLine:na,color=red,transp=0)

//--Overbought/Oversold/Warning Detail
UPshape = up > ob and up>down ? highest(up,1) + 20:up > ob and up<down?highest(down,1) + 20:na
DOWNshape = down < os and up>down ? lowest(down,1) - 20:down < os and up<down?lowest(up,1) - 20 :na
plot(UPshape,style=cross,color=aqua,linewidth=2,transp=0)
plot(DOWNshape,style=cross,color=aqua,linewidth=2,transp=0)
x1=OBOS?ob:false
x2=OBOS?os:false
hline(x1)
hline(x2)
//http://www.wisestocktrader.com/indicators/2739-flower-indicator
